#include "user.hpp"
#include "class.hpp"
#include "achievement.hpp"
#include "assignment.hpp"
#include "skills.hpp"
#include "task.hpp"
#include "account.hpp"
#include "vocab_screen.hpp"
#include "user_data.hpp"
#include "curriculum.hpp"
#include "curriculum_data.hpp"
#include "module.hpp"
#include "exam_data.hpp"
#include "exam_level.hpp"

#pragma once